### ISSUE TITLE
Ender.js build not working

### ISSUE THREAD

**Issue by benekastah** [jgallen23/resistance#2]
Building resistance with ender.js is failing silently. It pretends to build, and lists it when I check the status with `ender info`, but resistance is nowhere to be found in my ender.js file.

I am not sure if the problem is with resistance or with ender, so le me know if I should post this issue with ender instead.

**Comment by jgallen23** [comment]
just pushed a fix 1e36467

can you verify the fix?  you should be able to either do require('resistance') or $.runSeries, $.runParallel

**Comment by benekastah** [comment]
This seems to be working great. Thanks!
